plugins {
    id 'application'
}

group = 'com.example.urlshortener'
version = '1.0-SNAPSHOT'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

application {
    mainClass = providers.gradleProperty('mainClass')
            .orElse('com.example.urlshortener.lab.SnowflakeComparisonRunner')
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}
